name: dogcat_single_tyler
hyperparameters:
    learning_rate: .005
    global_batch_size: 32
    weight_decay: 1e-4
    nesterov: True
searcher:
    name: single
    metric: accuracy
    max_length:
        batches: 6250
    smaller_is_better: false
entrypoint: model_def:DogCatModel
min_validation_period:
  batches: 100
resources:
    slots_per_trial: 2
max_restarts: 0
